### ISSUE TITLE
Failure to run sync due to missing capabilities

### ISSUE THREAD

**Issue by skx** [molecule-man/stack-assembly#4]
When running `diff` I see changes to be applied, as expected, however attempting to run a sync operation fails:

```
failed to register changeset: failed to perform CreateChangeSet: InsufficientCapabilitiesException: Requires capabilities : [CAPABILITY_IAM]
	status code: 400, request id: e87a11b2-21fb-468b-9cea-7a9ea2b8bca8
```

If I were running the cloudformation subcommand of the `aws` tool I'd add:

```
 --capabilities CAPABILITY_IAM 
```

However with your tool I don't see the ability to do that.  Am I out of luck, or is there something that can be done?

**Comment by molecule-man** [comment]
It should be possible to provide capabilities by adding the `capabilities` entry into stack config. It should look something like this ;

```yaml
stacks:
    mystack:
        name: mystack
        path: path/to/my/stack.yml
        capabilities:
            - CAPABILITY_IAM
```
